
import type { Surah, Reciter, Stat, ReadingActivity, Translation, Verse, Bookmark } from './types';

export const allSurahs: Omit<Surah, 'verses'>[] = [
  { id: 1, name: 'الفاتحة', englishName: 'Al-Fatiha', total_verses: 7 },
  { id: 2, name: 'البقرة', englishName: 'Al-Baqarah', total_verses: 286 },
  { id: 3, name: 'آل عمران', englishName: 'Ali \'Imran', total_verses: 200 },
  { id: 4, name: 'النساء', englishName: 'An-Nisa', total_verses: 176 },
  { id: 5, name: 'المائدة', englishName: 'Al-Ma\'idah', total_verses: 120 },
  { id: 6, name: 'الأنعام', englishName: 'Al-An\'am', total_verses: 165 },
  { id: 7, name: 'الأعراف', englishName: 'Al-A\'raf', total_verses: 206 },
  { id: 8, name: 'الأنفال', englishName: 'Al-Anfal', total_verses: 75 },
  { id: 9, name: 'التوبة', englishName: 'At-Tawbah', total_verses: 129 },
  { id: 10, name: 'يونس', englishName: 'Yunus', total_verses: 109 },
  { id: 11, name: 'هود', englishName: 'Hud', total_verses: 123 },
  { id: 12, name: 'يوسف', englishName: 'Yusuf', total_verses: 111 },
  { id: 13, name: 'الرعد', englishName: 'Ar-Ra\'d', total_verses: 43 },
  { id: 14, name: 'ابراهيم', englishName: 'Ibrahim', total_verses: 52 },
  { id: 15, name: 'الحجر', englishName: 'Al-Hijr', total_verses: 99 },
  { id: 16, name: 'النحل', englishName: 'An-Nahl', total_verses: 128 },
  { id: 17, name: 'الإسراء', englishName: 'Al-Isra', total_verses: 111 },
  { id: 18, name: 'الكهف', englishName: 'Al-Kahf', total_verses: 110 },
  { id: 19, name: 'مريم', englishName: 'Maryam', total_verses: 98 },
  { id: 20, name: 'طه', englishName: 'Taha', total_verses: 135 },
  { id: 21, name: 'الأنبياء', englishName: 'Al-Anbya', total_verses: 112 },
  { id: 22, name: 'الحج', englishName: 'Al-Hajj', total_verses: 78 },
  { id: 23, name: 'المؤمنون', englishName: 'Al-Mu\'minun', total_verses: 118 },
  { id: 24, name: 'النور', englishName: 'An-Nur', total_verses: 64 },
  { id: 25, name: 'الفرقان', englishName: 'Al-Furqan', total_verses: 77 },
  { id: 26, name: 'الشعراء', englishName: 'Ash-Shu\'ara', total_verses: 227 },
  { id: 27, name: 'النمل', englishName: 'An-Naml', total_verses: 93 },
  { id: 28, name: 'القصص', englishName: 'Al-Qasas', total_verses: 88 },
  { id: 29, name: 'العنكبوت', englishName: 'Al-\'Ankabut', total_verses: 69 },
  { id: 30, name: 'الروم', englishName: 'Ar-Rum', total_verses: 60 },
  { id: 31, name: 'لقمان', englishName: 'Luqman', total_verses: 34 },
  { id: 32, name: 'السجدة', englishName: 'As-Sajdah', total_verses: 30 },
  { id: 33, name: 'الأحزاب', englishName: 'Al-Ahzab', total_verses: 73 },
  { id: 34, name: 'سبإ', englishName: 'Saba', total_verses: 54 },
  { id: 35, name: 'فاطر', englishName: 'Fatir', total_verses: 45 },
  { id: 36, name: 'يس', englishName: 'Ya-Sin', total_verses: 83 },
  { id: 37, name: 'الصافات', englishName: 'As-Saffat', total_verses: 182 },
  { id: 38, name: 'ص', englishName: 'Sad', total_verses: 88 },
  { id: 39, name: 'الزمر', englishName: 'Az-Zumar', total_verses: 75 },
  { id: 40, name: 'غافر', englishName: 'Ghafir', total_verses: 85 },
  { id: 41, name: 'فصلت', englishName: 'Fussilat', total_verses: 54 },
  { id: 42, name: 'الشورى', englishName: 'Ash-Shuraa', total_verses: 53 },
  { id: 43, name: 'الزخرف', englishName: 'Az-Zukhruf', total_verses: 89 },
  { id: 44, name: 'الدخان', englishName: 'Ad-Dukhan', total_verses: 59 },
  { id: 45, name: 'الجاثية', englishName: 'Al-Jathiyah', total_verses: 37 },
  { id: 46, name: 'الأحقاف', englishName: 'Al-Ahqaf', total_verses: 35 },
  { id: 47, name: 'محمد', englishName: 'Muhammad', total_verses: 38 },
  { id: 48, name: 'الفتح', englishName: 'Al-Fath', total_verses: 29 },
  { id: 49, name: 'الحجرات', englishName: 'Al-Hujurat', total_verses: 18 },
  { id: 50, name: 'ق', englishName: 'Qaf', total_verses: 45 },
  { id: 51, name: 'الذاريات', englishName: 'Adh-Dhariyat', total_verses: 60 },
  { id: 52, name: 'الطور', englishName: 'At-Tur', total_verses: 49 },
  { id: 53, name: 'النجم', englishName: 'An-Najm', total_verses: 62 },
  { id: 54, name: 'القمر', englishName: 'Al-Qamar', total_verses: 55 },
  { id: 55, name: 'الرحمن', englishName: 'Ar-Rahman', total_verses: 78 },
  { id: 56, name: 'الواقعة', englishName: 'Al-Waqi\'ah', total_verses: 96 },
  { id: 57, name: 'الحديد', englishName: 'Al-Hadid', total_verses: 29 },
  { id: 58, name: 'المجادلة', englishName: 'Al-Mujadila', total_verses: 22 },
  { id: 59, name: 'الحشر', englishName: 'Al-Hashr', total_verses: 24 },
  { id: 60, name: 'الممتحنة', englishName: 'Al-Mumtahanah', total_verses: 13 },
  { id: 61, name: 'الصف', englishName: 'As-Saf', total_verses: 14 },
  { id: 62, name: 'الجمعة', englishName: 'Al-Jumu\'ah', total_verses: 11 },
  { id: 63, name: 'المنافقون', englishName: 'Al-Munafiqun', total_verses: 11 },
  { id: 64, name: 'التغابن', englishName: 'At-Taghabun', total_verses: 18 },
  { id: 65, name: 'الطلاق', englishName: 'At-Talaq', total_verses: 12 },
  { id: 66, name: 'التحريم', englishName: 'At-Tahrim', total_verses: 12 },
  { id: 67, name: 'الملك', englishName: 'Al-Mulk', total_verses: 30 },
  { id: 68, name: 'القلم', englishName: 'Al-Qalam', total_verses: 52 },
  { id: 69, name: 'الحاقة', englishName: 'Al-Haqqah', total_verses: 52 },
  { id: 70, name: 'المعارج', englishName: 'Al-Ma\'arij', total_verses: 44 },
  { id: 71, name: 'نوح', englishName: 'Nuh', total_verses: 28 },
  { id: 72, name: 'الجن', englishName: 'Al-Jinn', total_verses: 28 },
  { id: 73, name: 'المزمل', englishName: 'Al-Muzzammil', total_verses: 20 },
  { id: 74, name: 'المدثر', englishName: 'Al-Muddaththir', total_verses: 56 },
  { id: 75, name: 'القيامة', englishName: 'Al-Qiyamah', total_verses: 40 },
  { id: 76, name: 'الانسان', englishName: 'Al-Insan', total_verses: 31 },
  { id: 77, name: 'المرسلات', englishName: 'Al-Mursalat', total_verses: 50 },
  { id: 78, name: 'النبإ', englishName: 'An-Naba', total_verses: 40 },
  { id: 79, name: 'النازعات', englishName: 'An-Nazi\'at', total_verses: 46 },
  { id: 80, name: 'عبس', englishName: '\'Abasa', total_verses: 42 },
  { id: 81, name: 'التكوير', englishName: 'At-Takwir', total_verses: 29 },
  { id: 82, name: 'الإنفطار', englishName: 'Al-Infitar', total_verses: 19 },
  { id: 83, name: 'المطففين', englishName: 'Al-Mutaffifin', total_verses: 36 },
  { id: 84, name: 'الإنشقاق', englishName: 'Al-Inshiqaq', total_verses: 25 },
  { id: 85, name: 'البروج', englishName: 'Al-Buruj', total_verses: 22 },
  { id: 86, name: 'الطارق', englishName: 'At-Tariq', total_verses: 17 },
  { id: 87, name: 'الأعلى', englishName: 'Al-A\'la', total_verses: 19 },
  { id: 88, name: 'الغاشية', englishName: 'Al-Ghashiyah', total_verses: 26 },
  { id: 89, name: 'الفجر', englishName: 'Al-Fajr', total_verses: 30 },
  { id: 90, name: 'البلد', englishName: 'Al-Balad', total_verses: 20 },
  { id: 91, name: 'الشمس', englishName: 'Ash-Shams', total_verses: 15 },
  { id: 92, name: 'الليل', englishName: 'Al-Layl', total_verses: 21 },
  { id: 93, name: 'الضحى', englishName: 'Ad-Duhaa', total_verses: 11 },
  { id: 94, name: 'الشرح', englishName: 'Ash-Sharh', total_verses: 8 },
  { id: 95, name: 'التين', englishName: 'At-Tin', total_verses: 8 },
  { id: 96, name: 'العلق', englishName: 'Al-\'Alaq', total_verses: 19 },
  { id: 97, name: 'القدر', englishName: 'Al-Qadr', total_verses: 5 },
  { id: 98, name: 'البينة', englishName: 'Al-Bayyinah', total_verses: 8 },
  { id: 99, name: 'الزلزلة', englishName: 'Az-Zalzalah', total_verses: 8 },
  { id: 100, name: 'العاديات', englishName: 'Al-\'Adiyat', total_verses: 11 },
  { id: 101, name: 'القارعة', englishName: 'Al-Qari\'ah', total_verses: 11 },
  { id: 102, name: 'التكاثر', englishName: 'At-Takathur', total_verses: 8 },
  { id: 103, name: 'العصر', englishName: 'Al-\'Asr', total_verses: 3 },
  { id: 104, name: 'الهمزة', englishName: 'Al-Humazah', total_verses: 9 },
  { id: 105, name: 'الفيل', englishName: 'Al-Fil', total_verses: 5 },
  { id: 106, name: 'قريش', englishName: 'Quraysh', total_verses: 4 },
  { id: 107, name: 'الماعون', englishName: 'Al-Ma\'un', total_verses: 7 },
  { id: 108, name: 'الكوثر', englishName: 'Al-Kawthar', total_verses: 3 },
  { id: 109, name: 'الكافرون', englishName: 'Al-Kafirun', total_verses: 6 },
  { id: 110, name: 'النصر', englishName: 'An-Nasr', total_verses: 3 },
  { id: 111, name: 'المسد', englishName: 'Al-Masad', total_verses: 5 },
  { id: 112, name: 'الإخلاص', englishName: 'Al-Ikhlas', total_verses: 4 },
  { id: 113, name: 'الفلق', englishName: 'Al-Falaq', total_verses: 5 },
  { id: 114, name: 'الناس', englishName: 'An-Nas', total_verses: 6 },
];

export const reciters: Reciter[] = [
    { id: '7', name: 'Mishary Rashid Alafasy', audio_url_path: 'Alafasy/mp3' },
    { id: '4', name: 'Abdur-Rahman as-Sudais', audio_url_path: 'Sudais/mp3' },
];

// This is now the single source of truth for the available translation.
export const activeTranslation: Translation = { 
    id: '85', 
    language: 'english', 
    name: 'Hilali & Khan', 
    author_name: 'Dr. T. U. al-Hilali and Dr. M. Khan'
};


export const readingStats: { [key: string]: Stat } = {
  versesRead: {
    title: 'Verses Read Today',
    value: '7',
    change: '+3',
    changeType: 'increase',
  },
  timeSpent: {
    title: 'Time Spent',
    value: '12m 45s',
    change: '+2m',
    changeType: 'increase',
  },
  readingStreak: {
    title: 'Reading Streak',
    value: '5 Days',
    change: '-1',
    changeType: 'decrease',
  },
};

export const readingActivity: ReadingActivity[] = [
  { day: 'Mon', minutes: 15 },
  { day: 'Tue', minutes: 25 },
  { day: 'Wed', minutes: 10 },
  { day: 'Thu', minutes: 30 },
  { day: 'Fri', minutes: 45 },
  { day: 'Sat', minutes: 20 },
  { day: 'Sun', minutes: 12 },
];

export const searchResults = [
  { surah: 'Al-Baqarah', verse: 255, text: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth...' },
  { surah: 'Al-Imran', verse: 133, text: 'And hasten to forgiveness from your Lord and a garden as wide as the heavens and earth, prepared for the righteous' },
  { surah: 'An-Nisa', verse: 29, text: 'O you who have believed, do not consume one another\'s wealth unjustly but only [in lawful] business by mutual consent. And do not kill yourselves [or one another]. Indeed, Allah is to you ever Merciful.' },
];

export const dailyAyah: Omit<Verse, 'id' | 'translation'> = {
  verse_key: '39:53',
  arabic: '۞ قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنْفُسِهِمْ لَا تَقْنَطُوا مِنْ رَحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ',
  translation: 'Say, "O My servants who have transgressed against themselves [by sinning], do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful."',
};

export const dailyHadith = {
  text: 'Narrated `Uthman bin `Affan: The Prophet (ﷺ) said, "The most superior among you (Muslims) are those who learn the Qur\'an and teach it."',
  source: 'Sahih al-Bukhari 5028'
};
